name: Docker Image CI

on:
  push:
    branches: [ "main" ]
 

jobs:

  DOCKER-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag test-build:$(date +%s)
    - name:  check the  docker images 
      run: docker images 
